### ISSUE TITLE
Question: Card padding

### ISSUE THREAD

**Issue by cohix** [GraphKit/MaterialKit#31]
I would like to add more padding around the title and description labels. How would I go about this?

**Comment by danieldahan** [comment]
If you update to the latest release 1.11.0, there are properties that may be set to add more spacing. 

For example:

// images
card.horizontalImageViewSpace = 32
card.verticalImageViewSpace = 32

// title
card.horizontalTitleLabelSpace = 32
card.verticalTitleLabelSpace = 32

// detail (description)
card.horizontalDetailLabelSpace = 32
card.verticalDetailLabelSpace = 32

// buttons	
card.horizontalButtonSpace = 32
card.verticalButtonSpace = 32

**Comment by cohix** [comment]
That is fantastic. Thank you very much.
