### ISSUE TITLE
Multiple line titleLabel

### ISSUE THREAD

**Issue by cohix** [GraphKit/MaterialKit#32]
I would like the option to enable multi-line titles. Something like this:

```
card.titleLabel!.lineBreakMode = NSLineBreakMode.ByWordWrapping
card.titleLabel!.numberOfLines = 0
```
could allow the title to be multi-line with the card resizing appropriately.

Thank you for the amazing library!

**Comment by adamdahan** [comment]
@cohix That's a good suggestion :) Thanks for the feedback - perhaps in the next few versions we will support that for all our cards.

**Comment by cohix** [comment]
Thank you!

Cheers,
Connor Hicks
On Mon, Sep 7, 2015 at 12:50 PM, GraphKit/MaterialKit
<reply@reply.github.com>
wrote:
@cohix [https://github.com/cohix] That's a good suggestion :) Thanks for the feedback - perhaps in the next few
versions we will support that for all our cards.

—
Reply to this email directly or view it on GitHub
[https://github.com/GraphKit/MaterialKit/issues/32#issuecomment-138339749] .[https://github.com/notifications/beacon/AFqsYms2JHvR4l8at3cnyDr0cQq6b6xxks5ovbfsgaJpZM4F5ARn.gif]

**Comment by cohix** [comment]
@adamdahan I see that you added some relevant code in the 1.12.0 release.. has this feature been fully implemented? If so, what is the process for enabling multi-line titles?

Cheers

**Comment by danieldahan** [comment]
@cohix The added code in 1.12.0 is to support the manipulation of autolayout within the card. The limitation of the multiline support is the height restriction on the tittleLabel property. The feature you are looking for is being discussed in 1.13.0.

**Comment by cohix** [comment]
Great, thank you! Godspeed :smile:

**Comment by cohix** [comment]
@adamdahan @danieldahan I needed this asap so I decided to implement it myself. I've finished it and tested. Would you be interested in a PR? See my fork.

**Comment by adamdahan** [comment]
@cohix go for it :)

**Comment by cohix** [comment]
It's only for BasicCardView thus far. I think I'll wait until I'm done with ImageCardView as well. @adamdahan

**Comment by adamdahan** [comment]
:+1: make sure you pr against the dev branch

**Comment by adamdahan** [comment]
@cohix :+1: make sure you pr against the dev branch

**Comment by adamdahan** [comment]
@danieldahan reopening ticket

**Comment by danieldahan** [comment]
@cohix This is now fixed in issue-41, which I am pushing as a PR to development. Once merged you can use the development branch if you would like to utilize the feature prior to 1.13
