### ISSUE TITLE
Swift 2 Release

### ISSUE THREAD

**Issue by cohix** [GraphKit/MaterialKit#46]
Are there plans for a swift v2 release?

**Comment by danieldahan** [comment]
Yes, we have the initial fixes in place. I would like to run some tests and ensure some cleanups get in there. You should see it tomorrow if not later tonight :)

**Comment by cohix** [comment]
Beautiful thank you!

**Comment by danieldahan** [comment]
@cohix Still testing away, should be done soon. All the best and sorry for any inconvenience.

**Comment by cohix** [comment]
@danieldahan Are you aware of the bug in MaterialButton in this block:
```private func prepareBackgroundColorView() {
		backgroundColorView.translatesAutoresizingMaskIntoConstraints = false
		backgroundColorView.layer.masksToBounds = true
		backgroundColorView.clipsToBounds = true
		backgroundColorView.userInteractionEnabled = false
		insertSubview(backgroundColorView, atIndex: 0)
		Layout.expandToParent(self, child: backgroundColorView)
	}
```
Where the insertSubview line fails with lldb?

**Comment by danieldahan** [comment]
Can you make an issue for that and I will look into it :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by cohix** [comment]
@danieldahan done!

**Comment by danieldahan** [comment]
thank you :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by cohix** [comment]
No worries. Good work guys :)

**Comment by kaushik-zapyle** [comment]
Is this fixed yet?

**Comment by danieldahan** [comment]
@kaushik-zapyle Currently the development branch works on iOS 9 with swift 2. There seems to be an issue that @cohix is facing, and at the moment, not reproducible on our end. There isn't an official release right now with iOS 9 support, as we are ensuring that there are not any edge cases we have not yet had a chance to expose. Have you tried the development branch within your project?

**Comment by kaushik-zapyle** [comment]
So pod install for development branch gives me unable to find specification for MaterialKit.

**Comment by cohix** [comment]
The pod name is MK

**Comment by danieldahan** [comment]
@cohix thank you :)

**Comment by cohix** [comment]
@danieldahan No worries :)

**Comment by kaushik-zapyle** [comment]
Thank you... :) :+1:
