### ISSUE TITLE
Turn off Pulse

### ISSUE THREAD

**Issue by WilliamHua** [GraphKit/MaterialKit#49]
Is there a way to turn off pulsation so that there is only the appearance that the button is being lifted / raised?

I've tried `button.pulseColor = UIColor.clearColor()` but that doesn't have the desired effect (there is still a dark pulse)

**Comment by danieldahan** [comment]
If you are on dev, you can do this: 

card.pulseColor = nil

What version are you using? I may be able to offer a workaround.

**Comment by WilliamHua** [comment]
Luckily I'm on the dev branch! Thanks, worked like a charm
