### ISSUE TITLE
Old style of image card

### ISSUE THREAD

**Issue by cohix** [GraphKit/MaterialKit#60]
Hello! I just got an update approved today with Swift 2 and MK so great work all around :)

Just curious about what happened to the old style of image card? I would like to have that style with the image above, title overlaid, and card content+buttons below.

Thanks!

**Comment by danieldahan** [comment]
That is awesome :) Yes, the next component will be the ImageCardView which we will have available latest Sunday. As you may have seen, we overhauled the entire framework to make it better all around. I will keep this issue open as the issue we will work on to release the ImageCardView.

**Comment by cohix** [comment]
Yes I perused the code and it looks fantastic. I'm updating to the latest release as we speak. Is there any way I can get the ImageCardView in the development branch or something like that?

**Comment by danieldahan** [comment]
I can push to have it done even faster for you :) And it will be in dev, in about a day.

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
btw, what is your app?

**Comment by cohix** [comment]
That would be much appreciated!

spottedu.co/mobile :) The update was just approved, so it's not live yet. Version 1.0.2 is the Swift 2 version.

**Comment by danieldahan** [comment]
Nice! Looks great :) Have a great weekend.

**Comment by cohix** [comment]
You as well!

**Comment by danieldahan** [comment]
ImageCardView has been added. Please download the latest release 1.20.0. If you need any help using the new interface, let us know :)

**Comment by cohix** [comment]
@danieldahan wonderful thanks!
