### ISSUE TITLE
Image card of varying size

### ISSUE THREAD

**Issue by cohix** [GraphKit/MaterialKit#63]
Is it possible for the ImageCardView to change the size of its image view to the width-height ratio of the UIImage being loaded into it?

**Comment by danieldahan** [comment]
So there isn't an actual UIImageView being used. That would make the card heavier than necessary. What is actually happening, the card uses an imageLayer that you can access. As well, the card itself will support an image background too. So to understand your question correctly, are you trying to make the card scale to the image size, so the card can support dynamic sizes of images?

**Comment by cohix** [comment]
Yes that's exactly what I'm looking for. If I load a portrait image, I would like the image layer to have the same portrait ratio. Is there an easy way to achieve this now?

**Comment by danieldahan** [comment]
I made the adjustment locally to achieve what you are looking for. In this version you don't have to do a thing, it will do it for you. With that said, I need to run the framework through some tests and I can push it up for you in a short while. Sound good?

**Comment by cohix** [comment]
That would be fantastic. Thank you as always. Any way I can buy you guys a round of beers?

**Comment by danieldahan** [comment]
It is a pleasure to make this available for everyone :) We will be doing some meet ups soon, and we would be happy to have a round then. As well, you are helping us make a better product, we appreciate that.

**Comment by cohix** [comment]
Anything I can do to help :+1: Keep me in the loop!

**Comment by danieldahan** [comment]
Hey, so the dynamic sizing of ImageCardView has been added. We took this opportunity to add a bunch of tweaks we wanted to get in. Also, there is an additional property, maxImageSize for ImageCardView that doesn't allow the image height to get too long, this avoids any awkward looking cards. You can either not set the maxImageSize value or set it to 0 and it will allow any dynamic height size. I'll leave it to you to explore the new features. 

Pro tip* We added a new layer called MaterialLayer. It is really lightweight compared to a UIView and MaterialView. So if you are looking for the neat abilities without the weight, that is a nice option. 

All the best :)

**Comment by cohix** [comment]
That's awesome! I'm testing now. Looks great!

**Comment by danieldahan** [comment]
great :)
