### ISSUE TITLE
Support for tap image closure

### ISSUE THREAD

**Issue by agilecohix** [GraphKit/MaterialKit#64]
Hi all,

I'd like the ability to provide a block that will run when the image in an ImageCardView is tapped:

```
card.tapImageBlock = {()
in
    // Do something here
}
```
Any thoughts?

P.S. I want to use this to open a lightbox with that image, if there is a way I can accomplish this now, please let me know.

**Comment by danieldahan** [comment]
Hey :) 

That is a very specific use case. Preferably, I would like to keep the card more generic. 

One way of doing it, could be to add a tag gesture on the card and see if the tab is within the bounds of the image frame, which you can access from the optional imageLayer property that is set when you add an image.

**Comment by agilecohix** [comment]
Yeah I understand. That is a decent workaround, I'm using a UITapGestureRecognizer right now and it's still buggy as hell.

**Comment by danieldahan** [comment]
Actually, an even better approach would be to subclass the ImageCardView, which is a subclass of MaterialPulseView. Override the touchesBegan method, and if the touch is within the imageLayer execute your lightbox, if not, call the super.touchesBegan method.

**Comment by danieldahan** [comment]
public override func touchesBegan(touches: Set<UITouch>, withEvent event: UIEvent?) {
		
		let point: CGPoint = layer.convertPoint(touches.first!.locationInView(self), fromLayer: layer)
		if true == imageLayer?.containsPoint(point) {
			...
		} else {
                      super.touchesBegan(touches, withEvent: event)
                }
	}

I haven't tested the code, though this is the idea.

**Comment by danieldahan** [comment]
You can do the same with touchesEnd, which may be better to keep the pulse in general, though, you have to call super in that case to shrink the pulse.

**Comment by agilecohix** [comment]
Ahh interesting idea. I'll experiment! Thanks :) 

(btw It's me, @cohix, I used the wrong account by accident)

**Comment by danieldahan** [comment]
Awesome :) How are you liking MaterialKit? We are planning a really awesome update shortly.

**Comment by agilecohix** [comment]
Liking it very much! I'm very happy with it so far

**Comment by danieldahan** [comment]
Great! Okay, after your experimentation, let us know how it worked out and close the ticket. All the best :)

**Comment by agilecohix** [comment]
Will do! Cheers.

**Comment by agilecohix** [comment]
I ended up using your solution, works quite well!
```
override func touchesEnded(touches: Set<UITouch>, withEvent event: UIEvent?)
    {
        let point: CGPoint = layer.convertPoint(touches.first!.locationInView(self), fromLayer: layer)
        
        if imageLayer!.containsPoint(point)
        {
            // Show ligntbox
        }

        super.touchesEnded(touches, withEvent: event)
    }
```
