### ISSUE TITLE
.GIF Support

### ISSUE THREAD

**Issue by agilecohix** [GraphKit/MaterialKit#65]
Hey, it's me again.. Looking to support animated gif's in ImageCardView. Any thoughts?

**Comment by danieldahan** [comment]
Hey, that is a good one, though it wouldn't make it into MaterialKit, it would be added to ContentKit. I made a ticket for that here: https://github.com/GraphKit/ContentKit/issues/8. If you are looking for a solution immediately, this may help: https://github.com/mayoff/uiimage-from-animated-gif. I am going to close this ticket here and if you like, please follow the one I placed above.
